services:  
  api:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - movu-db-dev

  movu-db-dev:
    image: postgres:16.9-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes: 
      - movu-db-dev-data:/var/lib/postgresql/data

volumes:
  movu-db-dev-data:
    driver: local
